; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.38"

; Modules
projects[admin_menu][version] = "3.0-rc5"

projects[advanced_help][version] = "1.3"

projects[ctools][version] = "1.7"

projects[colorbox][version] = "2.9"

projects[content_access][version] = "1.2-beta2"

projects[context][version] = "3.6"

projects[date][version] = "2.8"

projects[smart_ip][version] = "2.41"

projects[entity][version] = "1.6"

projects[fivestar][version] = "2.1"

projects[flag][version] = "3.6"

projects[flag_friend][version] = "2.0-alpha1"

projects[heartbeat][version] = "1.1"

projects[i18n][version] = "1.13"

projects[panels][version] = "3.5"

projects[invite][version] = "4.0-beta2"

projects[libraries][version] = "2.2"

projects[link][version] = "1.3"

projects[logintoboggan][version] = "1.5"

projects[plus1][version] = "1.0-alpha2"

projects[rate][version] = "1.7"

projects[rules][version] = "2.9"

projects[translation_helpers][version] = "1.0"

projects[user_relationships][version] = "1.0-alpha5"

projects[userpoints][version] = "1.1"

projects[variable][version] = "2.5"

projects[views][version] = "3.11"

projects[views_slideshow][version] = "3.1"

projects[votingapi][version] = "2.12"

projects[weather][version] = "2.11"

projects[youtube][version] = "1.6"

; Themes
projects[bootstrap][version] = "3.0"

projects[omega][version] = "4.4"

projects[zen][version] = "5.5"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[fatal: Not a git repository (or any parent up to mount parent ][download][type] = ""
projects[fatal: Not a git repository (or any parent up to mount parent ][download][url] = ""
projects[fatal: Not a git repository (or any parent up to mount parent ][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox-1.x][download][type] = ""
libraries[colorbox-1.x][download][url] = ""
libraries[colorbox-1.x][directory_name] = "colorbox-1.x"
libraries[colorbox-1.x][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

