<?php

/**
* Implementation of hook_permission().
*/
function about_coeus_permission() {
  return array(
    'access site page' => array(
      'title' => t('Access site page'),
      'description' => t('Use can access this site page'),
    ),
  );
}

/**
* Implementation of hook_menu().
*/
function about_coeus_menu() {
    $items = array();

    $items['about'] = array(
        'title' => 'About us ',
        'page callback' => 'about_us',
        'access callback' => TRUE ,
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );
    $items['about-coeus/site'] = array(
        'title' => 'About site ',
        'page callback' => 'about_site',
        'access callback' => TRUE,
        'access arguments' => array('access site page'),
        'type' => MENU_CALLBACK,
     );


    return $items;
}

function about_us() {
    $vars = array();
    $vars['type']="ul";
    $vars['title'] = "";
    $vars['attributes']=array("");
    $vars['items'][0]="This is a simple proof of concept module1";
    $vars['items'][1]="This is a simple proof of concept module2";
    $vars['items'][2]="This is a simple proof of concept module3";


    return  theme_item_list($vars);
}
function about_site () {

    $vars = array();
    $vars['type']= "ul";
    $vars['title']="";
    $vars['attributes']=array("");
    $vars['items'][0]="This a site just practicing Drupal7";
    $vars['items'][1]="Druapl is really great CMS !";
    return theme_item_list($vars);
}
